name: index-update-from-file

on:
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: heyitsmemark/update-azure-search-index@1.0.0
        with:
          azureSearchInstance: plop
          azureSearchAdminKey: ${{ secrets.AZURE_SEARCH_ADMIN_KEY }}
          indexName: plop
          indexDefinitionFile: ./test-definitions/index.json